repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: flake8
        additional_dependencies: [flake8-import-order]
      - id: mixed-line-ending
        args:
          - --fix=no
      - id: no-commit-to-branch
        args:
          - --branch=master
      - id: trailing-whitespace
